remote_theme: just-the-docs/just-the-docs
title: Embracing Digital Transformation Podcast
tagline: Finding the Lemonade when life throws you lemons
description: They say when life gives you lemons you should make lemonade. Making lemonade is not always easy or possible. For us, we found ourselves single in our 40’s with kids at home and starting life over again. Luckily we found each other, online no doubt. When we began blending families, schedules, traditions, and laundry, we discovered lots of lemons. Our podcast is a reflection on how we get through the hard times and enjoy the good times on our new journey together, all with ten kids in tow. Sometimes when life gives you lemons, you make lemon squares. Lemonade might come later.
logo: "./full-logo.png"
search_enabled: true
author: Darren W Pulsipher
aux_links:
  "Shop": "https://www.etsy.com/shop/DaisyBlossomCreation"
  "Podcast Site": "https://wheresthelemonade.transistor.fm/"
  "Youtube": "https://www.youtube.com/@wheresthelemonade"
  "Facebook Group": "https://www.facebook.com/100063490226908/"
google_analytics: G-SDCPXLJ9YG
twitter:
  username: darrenpulsipher
  card: summary
social:
  name: Darren Pulsipher
  links:
    - https://www.etsy.com/shop/DaisyBlossomCreation
    - https://wheresthelemonade.transistor.fm/
    - https://www.youtube.com/@wheresthelemonade
    - https://www.facebook.com/100063490226908/
